sigstore/sigstore-probers

- .github/workflows/ctlog-sth.yml
- .github/workflows/reusable-prober.yml
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
The pagerduty has the incorrect links coming to sigstore-probers instead of p-g-i.
* Fix the links to playbooks.
> Fix the links to playbooks.

- .github/workflows/reusable-prober.yml
Closes https://github.com/sigstore/public-good-instance/issues/1113
Let's try using a [Github Action for retrying a specific job](https://github.com/marketplace/actions/retry-step) to hopefully address some occasionally flakiness we see in the GHA environment. Occasionally the `sigstore-prober` job step will fail because it cannot find a variable that should be available in the GHA environment. The job runs as expected when we manually retry it.
By allowing retries on the sigstore-prober job, we can hopefully avoid alerting on this occasional flakiness and only alert on repeated failures.
> Use retry action for prober

- .github/workflows/reusable-prober.yml
https://github.com/sigstore/sigstore-probers/actions/runs/4075935157 failed on an upgrade to go.mod, but the underlying issue was that the cache was created on `ubuntu-latest` but one of the jobs was instructed to run on `ubuntu-20.04`. This created a GLIBC mismatch when compiling against Ubuntu 22 and then trying to execute on Ubuntu 20. 
This changes PR all jobs to use the same OS image, and also makes some tweaks to use the cache from `actions/setup-go` and set the go version to be used from the `prober/hack/toolz/go.mod` file.
This should make probers faster 🤞🏼
> reenable cache, ensure all runners use same OS version

- .github/workflows/reusable-prober.yml
https://github.com/sigstore/sigstore-probers/pull/48 re-enabled caching to improve prober job times. However, the cache feature within actions/setup-go does not provide the ability to customize the caching key, so we end up in a suboptimal situation where the cache only contains a subset of what is needed for each job. This PR separates into per-job caches which should provide appropriate isolation as well as improved latency.
> optimization: separate caches by job

- .github/workflows/reusable-prober.yml
fixes #839
As discussed on https://github.com/sigstore/public-good-instance/issues/552#issuecomment-1222666820 we need to add a flag to specify the oidc provider, that in this case needs to be set to github.
NONE
No documentation needed
> fix: add oidc-provider flag on cosign sign for probers

- .github/workflows/reusable-prober.yml
Closes: #1398
There is not timeout set for those jobs, and by default github sets it to 360 minutes. It means that any step that is stuck will cause this to run for 6 hours.
Adding a more sane timeout of 10 minutes to ensure that the job is completed on time, or abort if not.
NONE
None, it is a change on the CI
> fix: add a timeout of 10 minutes to the probers

- .github/workflows/reusable-prober.yml
I've seen this flaky prober failure 3x today alone:
```
main.go:74: error during command execution: signing [localhost:1338/image:3a1f45de473a6017e2a69c2df2a50ca6dda88f3e-5315414857]: getting signer: getting key from Fulcio: retrieving cert: error obtaining token: expired_token
```
it happens when the github oidc server is unavailable so cosign tries to use browser flow instead to get the auth token.
i've added in a check at the beginning to make sure we can retrieve the OIDC auth token; if we can't, then don't alert pager duty.
> If Github OIDC server is down, don't page oncall on failure

- .github/workflows/ctlog-sth.yml
each job usually takes 10 seconds so 2 minutes should be more than enough time.
> Add timeout to CT log prober

- .github/workflows/ctlog-sth.yml
this way if a job times out, or fails bc GHA is down, we won't get paged. we'll only get paged if the probe check actually failed.
> ctlog prober: only alert PD if probe_status is failed

- .github/workflows/reusable-prober.yml
We made the TUF timestamp expire more frequently.
> Lower expiration for TUF timestamp

- .github/workflows/prober-prod.yml
- .github/workflows/prober-staging.yml
- .github/workflows/reusable-prober.yml
Add a job to the reusable prober workflow to create an issue in sigstore/public-good-instance when one of the probes fails.
The new job needs a new input, SIGSTORE_BOT_PAT, configured as a secret for the sigstore/sigstore-probers repo. The PAT needs to belong to a user or bot that has permission to create issues with labels for sigstore/public-good-instance.
The new job creates the issue with a new `needs-assignee` label. A sibling job in sigstore/public-good-instance will react to new issues that have this label and add the active oncall engineer as the assignee.
Relates to https://github.com/sigstore/public-good-instance/issues/486
Depends on https://github.com/sigstore/community/pull/377
> Create github issues for alerts

- .github/actions/close-workflow-issue/action.yml
- .github/actions/open-workflow-issue/action.yml
actions/create-issue is used by root-signing and the private repo to file issues in those same repos based on workflow failures. It currently uses a bash script that in turn uses curl, tr, cut, rev, jq, sed and gh to manipulate the GitHub API: this seems quite fragile and is currently broken in private repos (curl authentication problem).
This commit adds two new actions open-workflow-issue, close-workflow-issue that should provide the same minimal functionality using javascript (a composite action that uses github-script).
Intent (if this is merged) is to
* update both root-signing and private repo to use these instead of create-issue
* after that remove actions/create-issue and scripts/create_issue.sh
Fixes #158 
1. We could just fix the curl authentication that is the current issue …
> Add replacement actions for create-issue

- .github/actions/close-workflow-issue/action.yml
- .github/actions/open-workflow-issue/action.yml
Fix a bug in the workflow issue handling: Some webhook payloads do not have a `workflow` field. Use `run.data.path` instead.
> Issue actions: fix workflow path use

- .github/actions/open-workflow-issue/action.yml
Variable substitution is not a best practice: avoid it.
The annoying part in github-script is that inputs are not exposed via any context object: We have to route through environment variables.
> actions: Avoid variable substitution in issue action

- .github/workflows/reusable-prober.yml
> wrap command in parens and fix repo target for issue

- .github/workflows/reusable-prober.yml
This reverts commit 3b28b424b66cff8c0ea3a10517965d45f1d1ded0 that was made because root-signing-staging metadata was within 15 days of expiry and prober was pinging on-call. This should not be an issue any more.
> Revert "drop target check to a 7 day window before paging (#207)"

- .github/workflows/reusable-prober.yml
addresses hitting dockerhub rate limits (as seen in https://github.com/sigstore/sigstore-probers/actions/runs/10397453607/job/28793180975#step:9:24)
> swap crane cp with docker push of cached image

- .github/workflows/reusable-prober.yml
root-signing migration to tuf-on-ci tooling means the preprod repository is now published to the projects GitHub Pages url. Otherwise the functionality is the same.
Timeline:
* this should be merged after root-signing has switched to tuf-on-ci (https://github.com/sigstore/root-signing/pull/1323 merge). EDIT: merge is done, all looks good
* publishing to prod (https://github.com/sigstore/root-signing/issues/1340) should be switched on after this PR merges
> Switch the preprod TUF url

- .github/workflows/prober-staging.yml
- .github/workflows/reusable-prober.yml
Add option for grpc_fulcio_url and set to the grpc://fulcio.sigstage.dev
During database migration it was noticed that the staging prober was failing, and it should not have been. We found it is referencing the prod endpoint (which was down due to maintenance)
> add fulcio grpc url

- .github/workflows/reusable-prober.yml
Applies the fix in https://github.com/sigstore/sigstore-probers/pull/278 to the `reusable-prober` default.
See https://github.com/sigstore/sigstore-probers/actions/runs/10762903903 for a sample failure.
NONE
N/A
> Fix production sigstore GRPC probes

- .github/workflows/reusable-prober.yml
cached docker images have been removed from the ubuntu24.04 image (per https://github.com/actions/runner-images/issues/10636) ... so when ubuntu-latest pointer moves in December, this will break our prober. 
Instead of pulling from docker hub and potentially running into rate limiting, this changes to pull from a container on GHCR which hopefully minimizes external flakes
> update docker ref to pull from GHCR image

- .github/workflows/tiles-fsck.yml
Use the published docker image instead of rebuilding the tool every time the cron job runs.
> Remove fsck build steps
