sigstore/sigstore-probers

.github/workflows/ctlog-sth.yml
Signed-off-by: Priya Wadhwa <priya@chainguard.dev>
=> Add CT Log prober

.github/workflows/build-tools-ci.yml
Signed-off-by: Priya Wadhwa <priya@chainguard.dev>
=> Add presubmit

.github/workflows/rate-limiting.yml
Signed-off-by: Priya Wadhwa <priya@chainguard.dev>
=> Add rate limiting prober

.github/workflows/rate-limiting.yml, .github/workflows/reusable-pager.yml, .github/workflows/reusable-prober.yml, pager-duty/go.mod, prober/hack/toolz/go.mod
Necessary for atomic.Bool in the rate limit prober
Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>
=> Update workflows to run with Go 1.19

.github/workflows/reusable-prober.yml
Signed-off-by: Bob Callaway <bcallaway@google.com>
=> disable module cache

.github/workflows/reusable-prober.yml
Getting paged for prober failures due to cosign v2 bump. These flags should fix that.
=> Add certificate-oidc-issuer and certificate-identity flags for cosign v2

.github/workflows/reusable-prober.yml
=> Set correct oidc issuer in e2e test

.github/workflows/reusable-prober.yml
These flags are required by cosign v2
=> Add certificate-oidc-issuer and certificate-identity to reusable prober

.github/workflows/reusable-prober.yml
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
The certificate identity varies between invocations. One example is:
`https://github.com/sigstore/sigstore-probers/.github/workflows/reusable-prober.yml@refs/heads/cosign-v2-flags-attestation`
So, change it to use regexp.
=> use regexp for certificate-identity because it varies.

.github/workflows/reusable-prober.yml
=> Add cosign v2 flags to another action missing them

.github/workflows/ctlog-sth.yml
I am trying to see if this will invoke the pager if the step fails.
=> Do not keep going if step fails.

.github/workflows/reusable-prober.yml
The oidc-provider is "github-actions", hardcoded in Cosign. The Cosign CLI docs said "github".
=> Fix provider for prober

.github/actions/create-issue/action.yaml
When called, it showed two problems:
- cannot pass permissions in the action, needs to be done at job level
- run job needs to have shell specified, done that
NONE
NONE
=> fix: update create issue action to solve issues

.github/workflows/build-tools-ci.yml, .github/workflows/rate-limiting.yml, .github/workflows/reusable-pager.yml, .github/workflows/reusable-prober.yml
When fixing the timeouts, I only did for sigstore probers but there are other jobs, such as signing or ci, that needed as well. Add for all missing jobs
Closes: #1443
NONE
NONE
=> fix: add timeout to jobs that needed

.github/scripts/create_issue.sh
Closes: #878
When we run the job for closing previous issues, we actually need to double check if there was a previous issue to close. If that is not the case, just skip this step.
NONE
NONE
=> fix: do not close issues when there is no previous one

.github/workflows/reusable-prober.yml
This gives us more fine grained expiration checks than the previous day granularity, which is useful since we've decreased the expiration of timestamp and there are times when it can be very close to 2 days til expiry (which is expected).
Ref https://github.com/sigstore/root-signing/pull/882
=> Change expiration to be unix timestamp

.github/workflows/reusable-prober.yml, go.work.sum
Preprod is always a future version of prod, so this should always succeed unless we've pushed invalid metadata.
Fixes #91
=> Test that cosign initialize works from prod to preprod

.github/workflows/reusable-prober.yml
Since the root is expiring within fifteen days, the root prober keeps failing. This PR temporarily changes the expiration check so that the job always returns a success until the new root signing is complete.
This PR will be reverted once the new root signing is complete.
=> The root prober workflow temporarily always passes

.github/workflows/reusable-prober.yml
The PagerDuty alert is still being triggered so I am temporarily commenting out the entire check expiration job. The [issue](https://github.com/sigstore/sigstore-probers/issues/112) tracking this has also been added as a comment.
=> Comment out the expiration check job

.github/workflows/reusable-prober.yml
Reverts sigstore/sigstore-probers#113. Reverts https://github.com/sigstore/sigstore-probers/pull/111 too
Closes https://github.com/sigstore/sigstore-probers/issues/112
=> Revert "Comment out the expiration check job"

.github/workflows/reusable-prober.yml
=> add logging groups on root-probe

.github/dependabot.yml
=> Add pager-duty to dependabot

.github/workflows/reusable-prober.yml
This adds a link to the [TUF alerting playbook](https://github.com/sigstore/public-good-instance/blob/main/playbooks/alerting/tuf.md) because I ending up using that playbook while responding to failing prober incidents caused by expiring timestamp metadata.
=> Add link to expiring tuf metadata playbook

.github/actions/close-workflow-issue/action.yml, .github/actions/open-workflow-issue/action.yml
Some event types have no payload at all: Don't use it in open-workflow-issue and close-workflow-issue
Fixes #172
=> actions: Avoid using the webhook payload

.github/workflows/reusable-prober.yml
Given that we have a signing event planned for this week, let's temporarily shorten this window to stop the paging.
=> drop prober window from 15 to 7 days

.github/workflows/reusable-prober.yml
=> drop prober to 3 days given pending merge

.github/workflows/reusable-prober.yml
=> Update prober window after rollout

.github/workflows/reusable-prober.yml
=> exit if we fail verify cmd

.github/workflows/reusable-prober.yml
=> drop 21 to 2 days now that we've seen dedup work

.github/workflows/reusable-prober.yml
=> drop target check to a 7 day window before paging

.github/workflows/reusable-prober.yml
=> drop prober alerts to 7 days given upcoming signing event

.github/workflows/reusable-prober.yml
=> drop preprod prober alerts to 7 days given upcoming signing event

.github/workflows/build-tools-ci.yml, prober/Makefile, prober/hack/toolz/go.mod, prober/hack/toolz/toolz.go
=> fix build test to use go.mod for selecting go version

.github/workflows/reusable-prober.yml
=> reset validity checks to 15 days post root migration

.github/workflows/prober-staging.yml
=> take off scheme from grpc prober field

.github/workflows/reusable-prober.yml
=> add check for all reported shards from a rekor instance

.github/workflows/build-publish-tools-container.yml, .github/workflows/reusable-pager.yml, .github/workflows/reusable-prober.yml
=> extract tools from container

.github/workflows/prober-prod.yml
=> stop checking TSA on prod

.github/workflows/prober-prod.yml
=> pass staging URL for now

.github/workflows/reusable-prober.yml
=> add issues:write perms to job that creates issues

.github/workflows/reusable-prober.yml
=> fix perms for reusable-prober

.github/workflows/prober-prod.yml, .github/workflows/prober-staging.yml
=> try again with perms

.github/workflows/prober-prod.yml
DNM until confirmed service is up and running
=> start probing TSA in production env

Dockerfile
This was missed in 0a4375a7 and is needed to avoid building the tool from within the fsck workflow.
=> Add tiles-fsck build step
